### model
model_name_or_path: /root/autodl-tmp/Qwen/Qwen2.5-7B

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: jys_pretrain
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2.5-base/lora/pretrain_demo

logging_steps: 1
save_steps: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
